### ISSUE TITLE
Add Orm Mapping in Documentation

### ISSUE THREAD

**Issue by k0pernikus** [artberri/BerriartSitemapBundle#3]
I was confused why `app/console doctrine:schema:update` wasn't updating my schema. My config.yml was setup for annotations, so I had to add this:

```
# app/config.yml
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ...                    
                    BerriartSitemapBundle:
                        type: yml
                        dir: Resources/config/doctrine
```
